#::PROJECT:CI:UPHP
default:
  tags:
    - shell

stages:
  - builder

uPHP Builder:
  stage: builder
  variables:
    GIT_DEPTH: 1
  before_script:
    - ci/ci-setup-environment
    - export PATH=$PWD/ci:$PWD:${PATH}
  script:
    - ci-builder
  after_script:
    - ci/ci-cleanup-environment
  artifacts:
    name: "uphp-build-log"
    paths:
      - .ci/
    expire_in: 1 week
    when: always
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "pipeline"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_TAG =~ /trigger/
