#!/bin/bash
set -eu
set -o pipefail
source "config.ci"
BASE=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

export PATH="${BASE}/ci:${PATH}"

run_build() {
local upstream="${1}"
  if pv="$(docker run --rm -q --pull always "${upstream}" php -r 'echo PHP_VERSION;')"
  then
    base="${upstream%%:*}"
    tag="${upstream%%*:}"
    if [[ ${tag} =~ -fpm-alpine$ ]]
    then
      FLAVOR="fpm-alpine"
    elif [[ ${tag} =~ -fpm$ ]]
    then
      FLAVOR="fpm"
    else
      printf -- "ERROR: unsupported PHP image flavor: '%s' ...\n" "${tag}"
      exit 200
    fi
    export VERSION="${pv}"
    export FLAVOR
    export UPSTREAM="${base}:${VERSION}-${FLAVOR}"
    image-builder
  else
    printf -- "ERROR: Failed to retrieve PHP version"
    shadow-text 3 "FAILED"
    exit 100
  fi
}

if [[ -n ${1:-} ]]
then
  run_build "${1}"
else
  for upstream in ${UPSTREAMS}
  do
    run_build "${upstream}"
  done
fi
