#!/bin/bash
set -eu
source "config.ci"
if [[ -n ${CI_REGISTRY:-} ]]
then
  echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY" &>/dev/null
fi
if [[ -n ${DOCKER_IO_USER:-} ]] && [[ -n ${DOCKER_IO_TOKEN:-} ]]
then
  echo "${DOCKER_IO_TOKEN}" | docker login -u "${DOCKER_IO_USER}" --password-stdin &>/dev/null
fi
docker run --quiet --privileged --rm tonistiigi/binfmt --install all &>/dev/null
docker buildx inspect "${DOCKER_BUILDER}" --bootstrap || docker buildx create --use --bootstrap --name "${DOCKER_BUILDER}"
